# Generated by Django 5.0.6 on 2024-05-14 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EPp_Lista',
            fields=[
                ('eplista_id', models.AutoField(primary_key=True, serialize=False)),
                ('lentes', models.BooleanField()),
                ('casco', models.BooleanField()),
                ('mameluco', models.BooleanField()),
                ('mascarilla', models.BooleanField()),
                ('guantes', models.BooleanField()),
                ('zapatos', models.BooleanField()),
                ('orejeras', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('prueba_id', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuestas', models.TextField()),
                ('fecha', models.DateField()),
                ('tiempo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_usuario', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=100)),
                ('contraseña', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('resultado_id', models.AutoField(primary_key=True, serialize=False)),
                ('intentos', models.IntegerField()),
                ('prueba_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.prueba')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EPPs',
            fields=[
                ('epps_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('eplista_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.epp_lista')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Confirmacion_riesgos',
            fields=[
                ('confir_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuarios')),
            ],
        ),
    ]
